#!/system/bin/sh

LOG_FILE=/data/local/00sys.log
busybox rm -f $LOG_FILE
busybox touch $LOG_FILE

#busybox sysctl -e -w kernel.sem='500 512000 64 2048'
busybox sysctl -e -w kernel.panic=0
busybox sysctl -e -w kernel.panic_on_oops=0
#busybox sysctl -e -w kernel.core_uses_pid=0
#busybox sysctl -e -w kernel.core_pattern=core
#busybox sysctl -e -w kernel.core_pipe_limit=0
#busybox sysctl -e -w kernel.real-root-dev=0
#busybox sysctl -e -w kernel.print-fatal-signals=0
#busybox sysctl -e -w kernel.ctrl-alt-del=0
#busybox sysctl -e -w kernel.ftrace_dump_on_oops=0
#busybox sysctl -e -w kernel.dmesg_restrict=0
#busybox sysctl -e -w kernel.kptr_restrict=0
#busybox sysctl -e -w kernel.randomize_va_space=1
#busybox sysctl -e -w kernel.max_lock_depth=0
#busybox sysctl -e -w kernel.blk_iopoll=1
#busybox sysctl -e -w kernel.msgmni=2048
#busybox sysctl -e -w kernel.msgmax=65536
busybox sysctl -e -w kernel.random.read_wakeup_threshold=1376
busybox sysctl -e -w kernel.random.write_wakeup_threshold=128
#busybox sysctl -e -w kernel.shmmni=4096
#busybox sysctl -e -w kernel.shmall=2097152
#busybox sysctl -e -w kernel.shmmax=268435456
#busybox sysctl -e -w kernel.threads-max=524288
#busybox sysctl -e -w kernel.threads-max=5000

# busybox sysctl -e -w net.unix.max_dgram_qlen=50
# busybox sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1
# busybox sysctl -e -w net.ipv4.route.flush=1
# busybox sysctl -e -w net.ipv4.tcp_rfc1337=1
# busybox sysctl -e -w net.ipv4.ip_no_pmtu_disc=0
# busybox sysctl -e -w net.ipv4.tcp_ecn=0
# busybox sysctl -e -w net.ipv4.tcp_timestamps=1
# busybox sysctl -e -w net.ipv4.tcp_sack=1
# busybox sysctl -e -w net.ipv4.tcp_fack=1
# busybox sysctl -e -w net.ipv4.tcp_window_scaling=1
# busybox sysctl -e -w net.ipv4.tcp_tw_recycle=1
# busybox sysctl -e -w net.ipv4.tcp_tw_reuse=1
# busybox sysctl -e -w net.ipv4.tcp_congestion_control=cubic
# busybox sysctl -e -w net.ipv4.tcp_frto=2
# busybox sysctl -e -w net.ipv4.tcp_frto_response=2
# busybox sysctl -e -w net.ipv4.tcp_low_latency=1
# busybox sysctl -e -w net.ipv4.tcp_mtu_probing=1
# busybox sysctl -e -w net.ipv4.tcp_workaround_signed_windows=1
# busybox sysctl -e -w net.ipv4.tcp_dsack=1
# busybox sysctl -e -w net.ipv4.ip_dynaddr=0
# busybox sysctl -e -w net.ipv4.tcp_syncookies=0
# busybox sysctl -e -w net.ipv4.tcp_synack_retries=2
# busybox sysctl -e -w net.ipv4.tcp_syn_retries=2
# busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1
# busybox sysctl -e -w net.ipv4.icmp_echo_ignore_broadcasts=1
# busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1
# busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1
# busybox sysctl -e -w net.ipv4.tcp_fin_timeout=30
# busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30
# busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5
# busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1800
# busybox sysctl -e -w net.ipv4.ip_forward=0
# busybox sysctl -e -w net.ipv4.conf.all.send_redirects=0
# busybox sysctl -e -w net.ipv4.conf.default.send_redirects=0
# busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1
# busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1
# busybox sysctl -e -w net.ipv4.conf.all.accept_source_route=0
# busybox sysctl -e -w net.ipv4.conf.default.accept_source_route=0
# busybox sysctl -e -w net.ipv4.conf.all.accept_redirects=0
# busybox sysctl -e -w net.ipv4.conf.default.accept_redirects=0
# busybox sysctl -e -w net.ipv4.conf.all.secure_redirects=0
# busybox sysctl -e -w net.ipv4.conf.default.secure_redirects=0
# busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=4096
# busybox sysctl -e -w net.core.netdev_max_backlog=2500
# busybox sysctl -e -w net.core.optmem_max=20480

# busybox sysctl -e -w net.ipv4.udp_rmem_min=6144
# busybox sysctl -e -w net.ipv4.udp_wmem_min=6144
# busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=1440000
# busybox sysctl -e -w net.ipv4.tcp_mem="57344 57344 524288"
# busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=1440000
# busybox sysctl -e -w net.core.rmem_max=2097152
# busybox sysctl -e -w net.core.wmem_max=2097152
# busybox sysctl -e -w net.core.rmem_default=262144
# busybox sysctl -e -w net.core.wmem_default=262144


busybox sysctl -e -w net.ipv6.conf.default.disable_ipv6=1
busybox sysctl -e -w net.ipv6.conf.all.disable_ipv6=1
#busybox sysctl -e -w net.ipv6.conf.all.use_tempaddr=2
#busybox sysctl -e -w net.ipv6.conf.default.use_tempaddr=2
#busybox sysctl -e -w net.ipv6.conf.all.temp_prefered_lft=3600
#busybox sysctl -e -w net.ipv6.conf.default.temp_prefered_lft=3600

#busybox sysctl -e -w fs.lease-break-time=10
#busybox sysctl -e -w fs.file-max=65536
#busybox sysctl -e -w fs.file-max=524288
#busybox sysctl -e -w fs.inotify.max_queued_events=32000
#busybox sysctl -e -w fs.inotify.max_user_instances=256
#busybox sysctl -e -w fs.inotify.max_user_watches=10240

#vm setting
# busybox sysctl -e -w vm.page-cluster=3
# busybox sysctl -e -w vm.min_free_order_shift=4
# busybox sysctl -e -w vm.oom_kill_allocating_task=0
# busybox sysctl -e -w vm.oom_dump_tasks=1
# busybox sysctl -e -w vm.block_dump=0
# busybox sysctl -e -w vm.panic_on_oom=0
# busybox sysctl -e -w vm.overcommit_memory=1
# busybox sysctl -e -w vm.laptop_mode=0
# busybox sysctl -e -w vm.vfs_cache_pressure=10
# busybox sysctl -e -w vm.dirty_expire_centisecs=500
# busybox sysctl -e -w vm.dirty_writeback_centisecs=3000
# busybox sysctl -e -w vm.dirty_background_ratio=5
# busybox sysctl -e -w vm.dirty_ratio=10
# busybox sysctl -e -w vm.swappiness=0

busybox sysctl -e -w vm.swappiness=10
# busybox sysctl -e -w vm.vfs_cache_pressure=10
# busybox sysctl -e -w vm.dirty_ratio=90
# busybox sysctl -e -w vm.dirty_background_ratio=5
# busybox sysctl -e -w vm.dirty_expire_centisecs=500
# busybox sysctl -e -w vm.dirty_writeback_centisecs=1000
