#!/system/bin/sh

LOG_FILE=/data/local/01cpu.log
busybox rm -f $LOG_FILE
busybox touch $LOG_FILE

#busybox sleep 30s
#mount -o rw,remount rootfs /
#mount -o rw,remount /system


# 384000 460800 600000 672000 787200 864000 960000 1248000 1440000
freq=1248000
governor="ondemand"
for i in 0 1 2 3 4 5;do
    echo "80" > /sys/devices/system/cpu/cpu$i/cpufreq/$governor/up_threshold

    # chmod 666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor 
    echo "$governor" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
    # chmod 444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor 

    # chmod 666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
    echo "$freq" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
    # chmod 444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
done

echo "0" > /sys/module/alarm_dev/parameters/debug_mask
echo "0" > /sys/module/binder/parameters/debug_mask

export sampling_rate=10000
export up_threshold=80

echo "" | busybox tee -a $LOG_FILE
echo "==> $( date +"%m-%d-%Y %H:%M:%S" ) cpu tweak done." | busybox tee -a $LOG_FILE
