#!/system/bin/sh

LOG_FILE=/data/local/05zipalign.log
ZIPALIGNDB=/data/local/zipalign.data
busybox rm -f $LOG_FILE
busybox touch $LOG_FILE

if [ ! -e /system/xbin/zipalign ]; then
    echo "" | tee -a $LOG_FILE
    echo "--> $( date +"%m-%d-%Y %H:%M:%S" ) zipalign not found!!" | busybox tee -a $LOG_FILE
    exit 1
fi

if [ ! -f $ZIPALIGNDB ]; then
    busybox touch $ZIPALIGNDB
fi


for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(busybox grep "$DIR/$APK" $ZIPALIGNDB | busybox wc -l) -gt 0 ] ; then
      echo "--> Already checked: $DIR/$APK" | busybox tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "--> Already aligned: $DIR/$APK" | busybox tee -a $LOG_FILE
        busybox grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
          echo "==> Now aligning: $DIR/$APK" | busybox tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
#        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        rm -f /cache/$APK
        busybox grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

echo "" | busybox tee -a $LOG_FILE
echo "==> $( date +"%m-%d-%Y %H:%M:%S" ) zipalign optimization done." | busybox tee -a $LOG_FILE
